#!/bin/bash
# line above is only for syntax highlighting

### Appearance

# Font
font pango:"Noto Sans" Regular 9

# Colours
# class                 border  backgr. text    indicator child_border
client.focused          #556988 #556988 #000000 #556988   #556988
client.focused_inactive #393C41 #43464B #FFFFFF #43464B   #393C41
client.unfocused        #393C41 #43464B #FFFFFF #43464B   #393C41
client.urgent           #FF6188 #FF6188 #000000 #FF6188   #FF6188
client.placeholder      #3465A4 #3465A4 #000000 #3465A4   #3465A4
client.background       #2D2A2E

# Wallpaper
output * bg "$HOME/Pictures/wallpapers/large_ev414a.png" fill
# output * bg #000000 solid_color

# curl https://kyuunex.s-ul.eu/static/TLr1JPJY.png --create-dirs -o "$HOME/Pictures/wallpapers/large_ev414a.png"
# sha256sum "$HOME/Pictures/wallpapers/large_ev414a.png" | grep -q "d5ee70b867c95297ed90bb5d92b479d6a5bdc597149e4dab37e8d254a361f297" && echo "Checksum verified" || echo "Checksum failed"
