#!/bin/bash
# line above is only for syntax highlighting

### Appearance

# Font
font pango:"Noto Sans" Regular 9

# Colours
# class                 border  backgr. text    indicator child_border
client.focused          #FF6188 #FF6188 #000000 #FF6188   #FF6188
client.focused_inactive #393C41 #43464B #FFFFFF #43464B   #393C41
client.unfocused        #393C41 #43464B #FFFFFF #43464B   #393C41
client.urgent           #662636 #662636 #000000 #662636   #662636
client.placeholder      #3465A4 #3465A4 #000000 #3465A4   #3465A4
client.background       #2D2A2E

# Wallpaper
output * bg "$HOME/.config/wallpaper-image" fill
