#!/bin/bash
# line above is only for syntax highlighting

### Appearance

# Font for window titles. Will also be used by the bar unless a different font
# is used in the bar {} block below.
font pango:Noto Sans 9

# This font is widely installed, provides lots of unicode glyphs, right-to-left
# text rendering and scalability on retina/hidpi displays (thanks to pango).
# font pango:DejaVu Sans Mono 8

# Colours
# class                 border  backgr. text    indicator child_border
client.focused          #556988 #556988 #000000 #556988   #556988
client.focused_inactive #393C41 #43464B #FFFFFF #43464B   #393C41
client.unfocused        #393C41 #43464B #FFFFFF #43464B   #393C41
client.urgent           #FF6188 #FF6188 #000000 #FF6188   #FF6188
client.placeholder      #3465A4 #3465A4 #000000 #3465A4   #3465A4
client.background       #2D2A2E

# Wallpaper
# exec --no-startup-id feh --no-fehbg --bg-fill "$HOME/Pictures/wallpapers/large_ev414a.png"

# curl https://kyuunex.s-ul.eu/static/TLr1JPJY.png --create-dirs -o "$HOME/Pictures/wallpapers/large_ev414a.png"
# sha256sum "$HOME/Pictures/wallpapers/large_ev414a.png" | grep -q "d5ee70b867c95297ed90bb5d92b479d6a5bdc597149e4dab37e8d254a361f297" && echo "Checksum verified" || echo "Checksum failed"
