#!/bin/bash
# line above is only for syntax highlighting

### Window specific overrides
# to get window classes for xwayland apps, run: xprop | grep -i 'class'
# to get app_id, run: `swaymsg -t get_tree`

# for_window [class=".*"] border pixel 2
# for_window [class="explorer.exe"] floating disable, border none
# for_window [class="^([^o].*|o[^s].*|os[^u].*|osu[^!].*|osu!.+)\.exe$"] floating enable
for_window [class="vmware"] border pixel 2
for_window [class="Vmware"] border pixel 2
for_window [app_id="virt-manager"] border pixel 2
for_window [class=".*.exe"] floating enable
for_window [app_id=".*.exe"] floating enable
for_window [app_id="pavucontrol-qt"] floating disable
for_window [class="anbox"] floating enable
# default_border none
# default_floating_border none

# KDE stuff
for_window [app_id="org.kde.kcalc"] floating enable
for_window [app_id="org.kde.polkit-kde-authentication-agent-1"] floating enable
for_window [app_id="org.kde.keditfiletype"] floating enable

# Dolphin file manager dialogs
for_window [title="Copying .*. Dolphin"] floating enable
for_window [title="Moving .*. Dolphin"] floating enable
for_window [title="Extracting Files .*. Dolphin"] floating enable
for_window [title="Compressing .*. files .*. Dolphin"] floating enable
for_window [title="Deleting .*. Dolphin"] floating enable
for_window [title="Sending .*. KDE Connect Daemon"] floating enable
for_window [title="Progress Dialog — Dolphin"] floating enable
for_window [title="File Already Exists — Dolphin"] floating enable

# Ark
for_window [title="File Already Exists — Ark"] floating enable
for_window [title="Extracting .*. files — Ark"] floating enable

# Steam
for_window [class="steam_app_.*"] floating enable
for_window [class="steam_proton"] floating enable
for_window [class="Steam"] border pixel 2
for_window [class="steam"] border pixel 2
for_window [class="steamwebhelper"] border pixel 2

# Games
for_window [class="onscripter-ru.*"] floating enable
for_window [class="spine"] floating enable
for_window [class="mupen64plus"] floating enable
for_window [class="rpcs3"] floating enable
for_window [class="RPCS3"] floating enable
# for_window [title="Higurashi*"] floating enable
for_window [app_id="osu!"] border none
# for_window [class="osu!.exe"] floating enable, border none
for_window [class="cs2"] floating enable

# Browsers
for_window [app_id="firefox"] border pixel 2
for_window [title="Firefox — Sharing Indicator" app_id="firefox"] floating enable
for_window [class="Chromium"] border pixel 2
for_window [class="chromium"] border pixel 2
for_window [app_id="chromium"] border pixel 2
for_window [class="brave-browser"] border pixel 2
for_window [class="Brave-browser"] border pixel 2

# Media viewers
for_window [class="gst-play-1.0"] floating enable
for_window [app_id="mpv"] floating enable
for_window [class="GStreamer"] floating enable
for_window [app_id="org.kde.gwenview"] floating enable
for_window [app_id="lximage-qt"] floating enable
for_window [app_id="spek"] floating enable

